# https://geomdl-shapes.readthedocs.io/en/latest/

# Use RTD v2 configuration
version: 2

# Use RTD latest python image
build:
  image: latest

# Build HTML and PDF docs
formats:
  - htmlzip
  - pdf

# Python options
python:
  version: 3
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true
